### ISSUE TITLE
hello,I would like to ask  where to check the code for compound interest.

### ISSUE THREAD

**Issue by PetalsOnaWet** [PancakeBunny-finance/Bunny#1]
hello, I would like to ask you where to check the code for compound interest. I would like to learn more about bunny's compound interest rules.

**Comment by Bunny-dev-510** [comment]
hi! @PetalsOnaWet 

First of all, sorry for answering too late.

We calculate compound interest (called APY) of each pools by running scripts in backgound every few minutes and store the results in our database. So, the code calculating APY is not uploaded in our repo. However, we can tell you how APY be calculate briefly. The APY calculation is as follows:

- For each pools, get amount of rewards in year based on current state. The calculation method varies regarding rewards token and target farming pools.
- We divide this yearly profit by current total balance for each pools. In this process, we convert the value to USD or BNB. Now we have APR(Annual Percentage Rate) of each pools.
- Finally, we can calculate APY supposing we compound every day. The equation is as follows(best display in light mode):

    <img src="https://render.githubusercontent.com/render/math?math=Pool_{APY} =(\frac{Pool_{APR}}{365}%2B1)^{365} - 1">

Please note that there are some differences depending on pool types.

Hope to help your question,
thank you.
